In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
d = pd.read_csv('D:\data\iris.csv')
print(d)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [3]:
df = pd.DataFrame(d)

In [4]:
df

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [5]:
new = pd.DataFrame([0,1,2,3,'Label'])
new

0
0      0
1      1
2      2
3      3
4  Label

In [6]:
df= pd.concat([new,df],ignore_index=True,axis=1)

In [7]:
df

0    1    2    3    4               5
0        0  4.9  3.0  1.4  0.2     Iris-setosa
1        1  4.7  3.2  1.3  0.2     Iris-setosa
2        2  4.6  3.1  1.5  0.2     Iris-setosa
3        3  5.0  3.6  1.4  0.2     Iris-setosa
4    Label  5.4  3.9  1.7  0.4     Iris-setosa
..     ...  ...  ...  ...  ...             ...
144    NaN  6.7  3.0  5.2  2.3  Iris-virginica
145    NaN  6.3  2.5  5.0  1.9  Iris-virginica
146    NaN  6.5  3.0  5.2  2.0  Iris-virginica
147    NaN  6.2  3.4  5.4  2.3  Iris-virginica
148    NaN  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 6 columns]

In [8]:
df.drop(0,axis=1,inplace=True)

In [9]:
df

1    2    3    4               5
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [10]:
y_data = df[5] 

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_data = encoder.fit_transform(y_data)
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
x_data = df[[1,2,3,4]]

In [13]:
x_data

1    2    3    4
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x_data,y_data,test_size=0.2,shuffle=True)

In [15]:
from sklearn import linear_model

In [16]:
df.groupby(5).size()

5
Iris-setosa        49
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [17]:
model1 = linear_model.LogisticRegression()

In [18]:
model1.fit(x_train,y_train)

C:\Users\Divyansh Tiwari\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [19]:
y_pred = model1.predict(x_test)
y_pred

array([1, 0, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 1, 0, 2, 1, 2, 1,
       1, 0, 0, 2, 2, 2, 2, 1])

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_test,y_pred,normalize=True)

0.9333333333333333

In [22]:
#RANDOM FOREST

In [30]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(n_estimators = 1 ,criterion='entropy')
model2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1)

In [31]:
y_pred2 = model2.predict(x_test)
y_pred2

array([1, 0, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 1, 0, 2, 1, 2, 1,
       1, 0, 0, 2, 2, 2, 2, 1])

In [32]:
accuracy_score(y_test,y_pred2,normalize=True)

0.9333333333333333